### ISSUE TITLE
14. Longest Common Prefix

### ISSUE THREAD

**Issue by angelicagardner** [angelicagardner/coding-challenges#11]
Problem description: https://leetcode.com/problems/longest-common-prefix/

**Comment by AviDaddyCodez** [comment]
Hey, I can help you solve this issue:

Assign me this problem & I'll figure it out!

**Comment by angelicagardner** [comment]
> Hey, I can help you solve this issue:
> 
> 
> 
> Assign me this problem & I'll figure it out!

Sure, thanks for the interest :)
