### ISSUE TITLE
9. Palindrome Number

### ISSUE THREAD

**Issue by angelicagardner** [angelicagardner/coding-challenges#5]
Problem description: https://leetcode.com/problems/palindrome-number/

**Comment by ByteJoseph** [comment]
Is it allowed to use only Go language?

**Comment by angelicagardner** [comment]
Hi @ByteJoseph thanks for your comment, I was a bit surprised to see it because this repo is just a personal project I'm setting up for my own routine but it's public so OK for anyone to interact with of course I just wasn't expecting someone to find it interesting :).

> Is it allowed to use only Go language?

I was planning on doing the solutions only in Go, just for me to practice that language better and also because I have a GitHub Action set up to execute tests included in any PR. But if you have any ideas to setup/allow multiple languages please share.

**Comment by angelicagardner** [comment]
Read there might be copyright issues with adding the problem description so will start to provide a link or reference to the original problem on the platform instead.
